package org.example.steamstoreservice.dto.model;

import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.List;

@Getter
@Setter
public class GameModel {
    private String id;      // Unique ID generated by MongoDB

    private String title;

    private String description;

    private BigDecimal price;

    private List<String> genres;

    private String developer;

    private String publisher;

    private int releaseYear;

    public List<ReviewModel> reviews;
}
